# 어플리케이션용 docker-compose.yml
version: '3.8'

services:
  jobs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=jobs
      - PORT=3000
    ports:
      - '3000:3000'

  laboratory:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=laboratory
      - PORT=3002
    ports:
      - '3002:3002'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=api
      - PORT=3001
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    ports:
      - '3001:3001'
