# 어플리케이션용 docker-compose.yml
version: '3.8'

services:
  jobs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=jobs
      - PORT=3000
      - TZ=Asia/Seoul
      - NODE_ENV=production
    env_file:
      - ./env/.env.production
    ports:
      - '3000:3000'

  laboratory:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=laboratory
      - PORT=3002
      - NODE_ENV=production
    env_file:
      - ./env/.env.production
    ports:
      - '3002:3002'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=api
      - PORT=3001
      - NODE_ENV=production
    env_file:
      - ./env/.env.production
    ports:
      - '3001:3001'
