name: ci

on:
  push:
    branches:
      - main

# PWD : /home/runner/work/jayden-tool-repo/jayden-tool-repo
env:
  LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
  LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
  LIGHTSAIL_USERNAME: ubuntu
  AWS_REGION: ap-northeast-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERID }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./batch
          push: true
          # target: prod #target은.. 아직뭔지모르니 주석처리
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: AWS Lightsail access and delete image and container stop
        run: |
          echo "$LIGHTSAIL_SSH_KEY" > private_key && chmod 600 private_key
          ssh -v -o StrictHostKeyChecking=no -i private_key ${LIGHTSAIL_USERNAME}@${LIGHTSAIL_HOST} "sudo docker stop ${REPO_NAME} && sudo docker rm ${REPO_NAME} && sudo docker rmi ${DOCKER_USERNAME}/${REPO_NAME}"
        env:
          LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
          LIGHTSAIL_USERNAME: ubuntu
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          REPO_NAME: ${{ github.event.repository.name }}
          LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}

      - name: AWS Lightsail access and image load and container run
        run: |
          echo "$LIGHTSAIL_SSH_KEY" > private_key && chmod 600 private_key
          ssh -v -o StrictHostKeyChecking=no -i private_key ${LIGHTSAIL_USERNAME}@${LIGHTSAIL_HOST} "sudo docker pull ${DOCKER_USERNAME}/${REPO_NAME}:latest && sudo docker run \
          -v /home/ubuntu/secret:/usr/src/app/secret \
          -d --name ${REPO_NAME} ${DOCKER_USERNAME}/${REPO_NAME}:latest"
        env:
          LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
          LIGHTSAIL_USERNAME: ubuntu
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          REPO_NAME: ${{ github.event.repository.name }}
          LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
